function msg = SetupCoherentChameleonLaser
global TP

%% Lccate and Create the Laser Object
TP.HW.Coherent.ChameleonLaser = serial(TP.D.Sys.Laser.Port,...
            'BaudRate',                 19200,...
            'Terminator',               'CR/LF');
fopen(TP.HW.Coherent.ChameleonLaser);
msg = '';

%% Check if the Laser if On 
while 1
    fprintf(TP.HW.Coherent.ChameleonLaser, 'PRINT LASER');
    cs = fscanf(TP.HW.Coherent.ChameleonLaser);
    if cs(end-2) == '1';    break;      end
    errordlg('The laser is NOT enabled yet. Please use the key to turn it ON');
    pause;
end
%% Set Laser Commands
    fprintf(TP.HW.Coherent.ChameleonLaser, ['WAVELENGTH='   TP.D.Sys.Laser.WAVELENGTH]);pause(0.01);
    msg = [msg fscanf(TP.HW.Coherent.ChameleonLaser)];
    fprintf(TP.HW.Coherent.ChameleonLaser, ['GDD='          TP.D.Sys.Laser.GDD]);       pause(0.01);
    msg = [msg fscanf(TP.HW.Coherent.ChameleonLaser)];
    pause(10);
    
%% Print Laser Check Report
Qs = {...
  'PRINT FAULTS', ...         % '0'
  'PRINT FAULT HISTORY', ...  % 'SYSTEM OK'
  'PRINT UF POWER', ...       % '1638'
      'PRINT CAVITY PEAK HOLD', ...   % '1'= On
      'PRINT CAVITY PZT MODE', ...	% '0'= Auto
      'PRINT CAVITY PZT X', ...
      'PRINT CAVITY PZT Y', ...
      'PRINT PUMP PEAK HOLD', ...     % '1'= On
      'PRINT PUMP PZT MODE', ...      % '0'= Auto
      'PRINT PUMP PZT X', ...
      'PRINT PUMP PZT Y', ...
      'PRINT MODELOCKED', ...
      'PRINT PUMP SETTING', ...
      'PRINT TUNING STATUS', ...
      'PRINT SEARCH MODELOCK', ...
      'PRINT HOMED', ...
      'PRINT WAVELENGTH', ...
      'PRINT STEPPER POSITION', ...
  'PRINT CURRENT', ...
  'PRINT DIODE1 CURRENT', ...
  'PRINT DIODE2 CURRENT', ...
      'PRINT BASEPLATE TEMP', ...
  'PRINT DIODE1 TEMP', ...
  'PRINT DIODE2 TEMP', ...
  'PRINT VANADATE TEMP', ...
  'PRINT LBO TEMP', ...
  'PRINT ETALON TEMP', ...
      'PRINT DIODE1 SET TEMP', ...
      'PRINT DIODE2 SET TEMP', ...
      'PRINT VANADATE SET TEMP', ...
      'PRINT LBO SET TEMP', ...
      'PRINT ETALON SET TEMP', ...
  'PRINT DIODE1 TEMP DRIVE', ...
  'PRINT DIODE2 TEMP DRIVE', ...
  'PRINT VANADATE DRIVE', ...
  'PRINT LBO DRIVE', ...
  'PRINT ETALON DRIVE', ...
      'PRINT DIODE1 HEATSINK TEMP', ...
      'PRINT DIODE2 HEATSINK TEMP', ...
      'PRINT LBO HEATER', ...
      'PRINT LIGHT REG STATUS', ...
  'PRINT DIODE1 SERVO STATUS', ...
  'PRINT DIODE2 SERVO STATUS', ...
  'PRINT VANADATE SERVO STATUS', ...
  'PRINT LBO SERVO STATUS', ...
  'PRINT ETALON SERVO STATUS', ...
      'PRINT DIODE1 HOURS', ...
      'PRINT DIODE2 HOURS', ...
      'PRINT HEAD HOURS', ...
  'PRINT DIODE1 VOLTAGE', ...
  'PRINT DIODE2 VOLTAGE', ...
      'PRINT SOFTWARE', ...
      'PRINT POWER SUPPLY ID', ...
      'PRINT AUTOMODELOCK', ...
      'PRINT TUNING LIMIT MAX', ...
      'PRINT TUNING LIMIT MIN', ...
  '?PZTXCM', ...
  '?PZTXCP', ...
  '?PZTXPM', ...
  '?PZTXPP', ...
  '?PZTYCM', ...
  '?PZTYCP', ...
  '?PZTYPM', ...
  '?PZTYPP', ...
  '?RH', ...
  '?SN', ...
  '?ST', ...
      '?GDDCURVE', ...
      '?GDD', ...
      '?GDDCURVEN', ...
      '?COMP', ...
      '?HMCOMP', ...
      '?GDDMAX', ...
      '?GDDMIN'};

for i = 1:length(Qs)
    fprintf(TP.HW.Coherent.ChameleonLaser, Qs{i});
    pause(0.01);
    cs = fscanf(TP.HW.Coherent.ChameleonLaser);
    msg = [msg cs];
    pause(0.01);
end
disp(msg)
  







