function msg = SetupNIDAQ
% This function setup NI-DAQ cards wiring, and fundamental tasks
% Terminal Definition is in SetupD
% Terminal comments here are updated @4/18/2013, just for reference.

%% import NI DAQmx class
import dabs.ni.daqmx.*

%% import handles and data
global TP
NI = TP.D.Sys.NI;

%% System
    TP.HW.NI.hSys = System();    
        
%% Device and Reset
    for i = 1:length(TP.D.Sys.NI.Dev_Names) 
        TP.HW.NI.hDev{i} = Device(TP.D.Sys.NI.Dev_Names{i});
        TP.HW.NI.hDev{i}.reset();
    end

%% Timing Routing
    % Export Timebase to bridge, (/Dev1/20MHzTimebase to /Dev1/RTSI7)
    TP.HW.NI.hSys.connectTerms(...
        ['/', NI.Sys_TimingSource{1},'/',NI.Sys_TimingSource{2}],...
        ['/', NI.Sys_TimingSource{1},'/',NI.Sys_TimingBridge{2}]); 
   
%% HOUSE KEEPING TASKS
% AO_6115       for PMT Gain & AOD Amp Control
% DO_6115       for PMT Power Control
% DI_6115       for PMT Status Monitor
% AI_6323       for SYSTEM Status Monitor

% AO_6115 for PMT Gain and AOD Amp Control
% Dev1/AO 0:1, [PMT#1 Gain Ctrl, AOD Amp Ctrl]
    TP.HW.NI.T.hTask_AO_6115 = Task(NI.Task_AO_6115_Name);        
    TP.HW.NI.T.hTask_AO_6115.createAOVoltageChan(...
        NI.Chan_AO_PMT_CtrlGain{1},  	NI.Chan_AO_PMT_CtrlGain{2},...
        NI.Chan_AO_PMT_CtrlGain{3},     NI.Chan_AO_PMT_CtrlGain{4}(1),...
        NI.Chan_AO_PMT_CtrlGain{4}(2),	'DAQmx_Val_Volts'); 
    TP.HW.NI.T.hTask_AO_6115.createAOVoltageChan(...
        NI.Chan_AO_AOD_CtrlAmps{1},   	NI.Chan_AO_AOD_CtrlAmps{2},...
        NI.Chan_AO_AOD_CtrlAmps{3},   	NI.Chan_AO_AOD_CtrlAmps{4}(1),...
        NI.Chan_AO_AOD_CtrlAmps{4}(2), 	'DAQmx_Val_Volts');
    TP.HW.NI.T.hTask_AO_6115.writeAnalogData(...
        [TP.D.Mon.PMT.CtrlGainValue     TP.D.Mon.Power.AOD_CtrlAmpValue]);
    
% DO_6115 for PMT Power Control
% Dev1/line0:2, [PMTon, FANoff, PELTIERoff]  
    TP.HW.NI.T.hTask_DO_6115 = Task(NI.Task_DO_6115_Name);
    TP.HW.NI.T.hTask_DO_6115.createDOChan(...
        NI.Chan_DO_PMT_Switch{1},    	NI.Chan_DO_PMT_Switch{2});
        for i = 1:length(NI.Chan_DO_PMT_Switch{3})
            eval(['PMT_Ctrl(i,1)=logical(', NI.Chan_DO_PMT_Switch{3}{i},');']);
        end  
    TP.HW.NI.T.hTask_DO_6115.writeDigitalData(PMT_Ctrl);
    
% DI_6115 for PMT Status Monitor
% Dev1/line4:6 [PMT Status, Err, M9012]
    TP.HW.NI.T.hTask_DI_6115 = Task(NI.Task_DI_6115_Name);
    TP.HW.NI.T.hTask_DI_6115.createDIChan(...
        NI.Chan_DI_PMT_Status{1},   	NI.Chan_DI_PMT_Status{2});   
    
% AI_6323 for SYSTEM Status Monitor
% Dev3/AI ?:?+2: [PMT#1 Gain Mont, AOD X Amp Mont, AOD Y Amp Mont]
    TP.HW.NI.T.hTask_AI_6323 = Task(NI.Task_AI_6323_Name);
    TP.HW.NI.T.hTask_AI_6323.createAIVoltageChan(...
        NI.Chan_AI_PMT_MontGain{1},     NI.Chan_AI_PMT_MontGain{2},...
        NI.Chan_AI_PMT_MontGain{3},     NI.Chan_AI_PMT_MontGain{4}(1),...
        NI.Chan_AI_PMT_MontGain{4}(2), 	'DAQmx_Val_Volts');
    TP.HW.NI.T.hTask_AI_6323.createAIVoltageChan(...
        NI.Chan_AI_AOD_MontAmpX{1},    	NI.Chan_AI_AOD_MontAmpX{2},...
        NI.Chan_AI_AOD_MontAmpX{3},     NI.Chan_AI_AOD_MontAmpX{4}(1),...
        NI.Chan_AI_AOD_MontAmpX{4}(2),  'DAQmx_Val_Volts');
    TP.HW.NI.T.hTask_AI_6323.createAIVoltageChan(...
        NI.Chan_AI_AOD_MontAmpY{1},    	NI.Chan_AI_AOD_MontAmpY{2},...
        NI.Chan_AI_AOD_MontAmpY{3},     NI.Chan_AI_AOD_MontAmpY{4}(1),...
        NI.Chan_AI_AOD_MontAmpY{4}(2),  'DAQmx_Val_Volts');
    TP.HW.NI.T.hTask_AI_6323.cfgSampClkTiming(...
        NI.Task_AI_6323_SR,             'DAQmx_Val_ContSamps',...
        NI.Task_AI_6323_SmplToUpdt*4);
        % Continuous sampling, with buffer size = per update *4
 	TP.HW.NI.T.hTask_AI_6323.set(...
        'sampClkTimebaseRate',          NI.Sys_TimingRate,...
        'sampClkTimebaseSrc',           NI.Sys_TimingBridge{2});
    TP.HW.NI.T.hTask_AI_6323.registerEveryNSamplesEvent(...
        NI.Task_AI_6323_UpdateFunc,     NI.Task_AI_6323_SmplToUpdt,...
        true,                           'scaled');
    % link the callback function
    TP.HW.NI.T.hTask_AI_6323.start();    
    
%% SCANNING TASK
% DO_6536 for AOD Scanning
% Dev2/port0:3 Y15bit, Ycs, X15bit, Xcs
   	TP.HW.NI.T.hTask_DO_6536 = Task(NI.Task_DO_6536_Name);
   	TP.HW.NI.T.hTask_DO_6536.createDOChan(...
        NI.Chan_DO_Scan{1},         	NI.Chan_DO_Scan{2});
    
%% IMAGING TASK
% AI_6115 for PMT Imaging
% Dev1/AI0: PMT Signal, connected as pseudodiff configuration mode
    TP.HW.NI.T.hTask_AI_6115 = Task(NI.Task_AI_6115_Name);
	TP.HW.NI.T.hTask_AI_6115.createAIVoltageChan(...
        NI.Chan_AI_PMT1{1},             NI.Chan_AI_PMT1{2},...
        NI.Chan_AI_PMT1{3},             NI.Chan_AI_PMT1{4}(1),...
        NI.Chan_AI_PMT1{4}(2),          'DAQmx_Val_Volts');    
          
%% TIMING TASKS
% Internal Triger
    TP.HW.NI.T.hTask_CO_IntTrig = Task(NI.Task_CO_IntTrig_Name);
    TP.HW.NI.T.hTask_CO_IntTrig.createCOPulseChanTicks(...
        NI.Chan_CO_IntTrig{1},          NI.Chan_CO_IntTrig{2},...
        NI.Chan_CO_IntTrig{3},          NI.Chan_CO_IntTrig{5},...
        NI.Chan_CO_IntTrig{4}(1),    	NI.Chan_CO_IntTrig{4}(2) );%,...
%         NI.Chan_CO_IntTrig{6},          NI.Chan_CO_IntTrig{7});
    TP.HW.NI.T.hTask_CO_IntTrig.cfgImplicitTiming(...
        'DAQmx_Val_FiniteSamps',        1);
    
% Trigger Listener
    TP.HW.NI.T.hTask_CO_TrigListener = Task(NI.Task_CO_TrigListener_Name);
    TP.HW.NI.T.hTask_CO_TrigListener.createCOPulseChanTicks(...
        NI.Chan_CO_TrigListener{1},   	NI.Chan_CO_TrigListener{2},...
        NI.Chan_CO_TrigListener{3},     NI.Chan_CO_TrigListener{5},...
        NI.Chan_CO_TrigListener{4}(1),  NI.Chan_CO_TrigListener{4}(2) );%,...
%         NI.Chan_CO_TrigListener{6},     NI.Chan_CO_TrigListener{7});
    TP.HW.NI.T.hTask_CO_TrigListener.cfgDigEdgeStartTrig(...
        NI.Sys_TrigBridge{2},           'DAQmx_Val_Rising');    
    TP.HW.NI.T.hTask_CO_TrigListener.registerDoneEvent(...
        NI.Task_CO_TrigListener_Func);
    
% Stop Listener
    TP.HW.NI.T.hTask_CO_StopListener = Task(NI.Task_CO_StopListener_Name);
    TP.HW.NI.T.hTask_CO_StopListener.createCOPulseChanTicks(...
        NI.Chan_CO_StopListener{1},   	NI.Chan_CO_StopListener{2},...
        NI.Chan_CO_StopListener{3},     NI.Chan_CO_StopListener{5},...
        NI.Chan_CO_StopListener{4}(1),  NI.Chan_CO_StopListener{4}(2) );%,...
%         NI.Chan_CO_StopListener{6},     NI.Chan_CO_StopListener{7});
    TP.HW.NI.T.hTask_CO_StopListener.cfgDigEdgeStartTrig(...
        NI.Sys_TrigBridge{2},           'DAQmx_Val_Falling');    
    TP.HW.NI.T.hTask_CO_StopListener.registerDoneEvent(...
        NI.Task_CO_StopListener_Func);
        
%% LOG MSG
msg = [datestr(now, 'yy/mm/dd HH:MM:SS.FFF') '\tSetupNIDAQ\tNI-DAQmx tasks initialized\r\n'];
updateMsg(TP.D.Exp.hLog, msg);
